[package]
name = "rsm"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"
crate-type = ["staticlib"]

[dependencies]
shared_memory = "0.12.4"
raw_sync = "0.1.5"
log = "0.4.19"
env_logger = "0.10.0"
fastrand = "2.0.0"
